### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by mffap** [mffap/aboutauth#15]
- [x] Google Tag
- [x] Configure [docusaurus](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-tag-manager)
- [x] Install [cookie consent banner](https://github.com/68publishers/cookie-consent?tab=readme-ov-file)
- [x] Configure cookie consent banner
- [x] Create a privacy policy
